/* Auto-generated by psvita-toolkit from decompiled/apk_jadx/sources -- FalsoJNI callback candidates. */
/* Every entry here is a CANDIDATE: confirm the method belongs on the .so's actual call path, and */
/* read the real Java implementation (jadx) before trusting the stub body. See docs/dev-notes/jni_analyzer.md. */
#pragma once
#include <stdarg.h>
#include <falso_jni/FalsoJNI_Impl.h>

extern jint stub_GLMediaPlayer_getMusicDuration_0(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_getSoundDuration_1(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_getSoundStatus_2(jmethodID id, va_list args);
extern jfloat stub_GLMediaPlayer_getVolume_3(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_init_4(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_isMediaPlaying_5(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_isMusicPlaying_6(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_isSoundLoaded_7(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadMusic_8(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadSound_9(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadSoundPool_10(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseAllMusic_11(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseAllSound_12(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseAllSounds_13(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseMusic_14(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseMusicAsSound_15(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseSound_16(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_playMusic_17(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_playMusicAsSound_18(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_playSound_19(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resetSound_20(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resumeAllSound_21(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resumeMusic_22(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resumeMusicAsSound_23(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resumeSound_24(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_setVolume_25(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopAllMusic_26(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopAllSounds_27(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopMusic_28(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopMusicAsSound_29(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopSound_30(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_unloadMusic_31(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_unloadSound_32(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_updateSound_33(jmethodID id, va_list args);
extern void stub_GLResLoader_destroy_34(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getRawResource_35(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceBytes_36(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceFull_37(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceFull_38(jmethodID id, va_list args);
extern jint stub_GLResLoader_getResourceLength_39(jmethodID id, va_list args);
extern jint stub_GLResLoader_getResourceLengthSoundRaw_40(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getSoundRaw_41(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getSoundRawIS_42(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getString_43(jmethodID id, va_list args);
extern void stub_GLResLoader_init_44(jmethodID id, va_list args);
extern jobject stub_Device_Device_45(jmethodID id, va_list args);
extern void stub_Device_InitDeviceValues_46(jmethodID id, va_list args);
extern jboolean stub_Device_IsWifiEnable_47(jmethodID id, va_list args);
extern jobject stub_Device_ValidateStringforURL_48(jmethodID id, va_list args);
extern jobject stub_Device_a_49(jmethodID id, va_list args);
extern jobject stub_Device_b_50(jmethodID id, va_list args);
extern jobject stub_Device_c_51(jmethodID id, va_list args);
extern jint stub_Device_createUniqueCode_52(jmethodID id, va_list args);
extern jobject stub_Device_d_53(jmethodID id, va_list args);
extern void stub_Device_e_54(jmethodID id, va_list args);
extern jobject stub_Device_f_55(jmethodID id, va_list args);
extern jobject stub_Device_getCarrier_56(jmethodID id, va_list args);
extern jobject stub_Device_getDemoCode_57(jmethodID id, va_list args);
extern jobject stub_Device_getDevice_58(jmethodID id, va_list args);
extern jobject stub_Device_getHostName_59(jmethodID id, va_list args);
extern jobject stub_Device_getIMEI_60(jmethodID id, va_list args);
extern jboolean stub_Device_getIsRoaming_61(jmethodID id, va_list args);
extern jobject stub_Device_getLanguage_62(jmethodID id, va_list args);
extern jobject stub_Device_getLineNumber_63(jmethodID id, va_list args);
extern jobject stub_Device_getNetworkCountryIso_64(jmethodID id, va_list args);
extern jobject stub_Device_getNetworkOperator_65(jmethodID id, va_list args);
extern jobject stub_Device_getNetworkOperatorName_66(jmethodID id, va_list args);
extern jobject stub_Device_getPhoneModel_67(jmethodID id, va_list args);
extern jobject stub_Device_getSimCountryIso_68(jmethodID id, va_list args);
extern jobject stub_Device_getSimOperator_69(jmethodID id, va_list args);
extern jobject stub_Device_getSimOperatorName_70(jmethodID id, va_list args);
extern jint stub_Device_getUniqueCode_71(jmethodID id, va_list args);
extern jobject stub_Device_getUserAgent_72(jmethodID id, va_list args);
extern void stub_Device_init_73(jmethodID id, va_list args);
extern jboolean stub_GLiveMain_Autologin_74(jmethodID id, va_list args);
extern jobject stub_GLiveMain_Password_75(jmethodID id, va_list args);
extern jobject stub_GLiveMain_UserName_76(jmethodID id, va_list args);
extern void stub_GLiveMain_a_77(jmethodID id, va_list args);
extern void stub_GLiveMain_autoScaleTextViewTextToWidth_78(jmethodID id, va_list args);
extern void stub_GLiveMain_initBadge_79(jmethodID id, va_list args);
extern void stub_GLiveMain_initialize_Trophy_80(jmethodID id, va_list args);
extern jboolean stub_GLiveMain_needToRemoveFacebook_81(jmethodID id, va_list args);
extern void stub_GLiveMain_notifyTrophy_82(jmethodID id, va_list args);
extern void stub_GLiveMain_updateBadge_83(jmethodID id, va_list args);
extern void stub_GLiveMain_updateWebView_84(jmethodID id, va_list args);
extern void stub_GLiveMain_writeLoginInfo_85(jmethodID id, va_list args);
extern void stub_GLiveMain_a_86(jmethodID id, va_list args);
extern void stub_GLiveMain_a_87(jmethodID id, va_list args);
extern void stub_GLiveMain_a_88(jmethodID id, va_list args);
extern void stub_GLiveMain_onCreate_89(jmethodID id, va_list args);
extern void stub_GLiveMain_onDestroy_90(jmethodID id, va_list args);
extern jboolean stub_GLiveMain_onKeyDown_91(jmethodID id, va_list args);
extern jboolean stub_GLiveMain_onKeyLongPress_92(jmethodID id, va_list args);
extern jboolean stub_GLiveMain_onKeyUp_93(jmethodID id, va_list args);
extern void stub_GLiveMain_onPause_94(jmethodID id, va_list args);
extern void stub_GLiveMain_onResume_95(jmethodID id, va_list args);
extern void stub_GLiveMain_onWindowFocusChanged_96(jmethodID id, va_list args);
extern void stub_Game_DismissSpinner_97(jmethodID id, va_list args);
extern void stub_Game_Exit_98(jmethodID id, va_list args);
extern jint stub_Game_GetPhoneLanguage_99(jmethodID id, va_list args);
extern void stub_Game_Pause_100(jmethodID id, va_list args);
extern void stub_Game_SetReorientation_101(jmethodID id, va_list args);
extern void stub_Game_ShowSpinner_102(jmethodID id, va_list args);
extern void stub_Game_d_103(jmethodID id, va_list args);
extern jobject stub_Game_da_104(jmethodID id, va_list args);
extern jobject stub_Game_db_105(jmethodID id, va_list args);
extern jobject stub_Game_dc_106(jmethodID id, va_list args);
extern void stub_Game_enableWifi_107(jmethodID id, va_list args);
extern jint stub_Game_getManufacture_108(jmethodID id, va_list args);
extern jboolean stub_Game_isNeedGcOnFrame_109(jmethodID id, va_list args);
extern jboolean stub_Game_isNeedUsedTouchZone_110(jmethodID id, va_list args);
extern jint stub_Game_isWifiEnabled_111(jmethodID id, va_list args);
extern void stub_Game_launchGLLive_112(jmethodID id, va_list args);
extern void stub_Game_launchIGP_113(jmethodID id, va_list args);
extern void stub_Game_launchIGP_SKT_114(jmethodID id, va_list args);
extern void stub_Game_notifyTrophy_115(jmethodID id, va_list args);
extern void stub_Game_openBrowser_116(jmethodID id, va_list args);
extern void stub_Game_playVideo_117(jmethodID id, va_list args);
extern void stub_Game_sendAppToBackground_118(jmethodID id, va_list args);
extern void stub_Game_onAccuracyChanged_119(jmethodID id, va_list args);
extern void stub_Game_onCreate_120(jmethodID id, va_list args);
extern void stub_Game_onDestroy_121(jmethodID id, va_list args);
extern jboolean stub_Game_onKeyDown_122(jmethodID id, va_list args);
extern jboolean stub_Game_onKeyLongPress_123(jmethodID id, va_list args);
extern jboolean stub_Game_onKeyUp_124(jmethodID id, va_list args);
extern void stub_Game_onPause_125(jmethodID id, va_list args);
extern void stub_Game_onRestart_126(jmethodID id, va_list args);
extern void stub_Game_onResume_127(jmethodID id, va_list args);
extern jboolean stub_Game_onSearchRequested_128(jmethodID id, va_list args);
extern void stub_Game_onSensorChanged_129(jmethodID id, va_list args);
extern void stub_Game_onStart_130(jmethodID id, va_list args);
extern void stub_Game_onStop_131(jmethodID id, va_list args);
extern jobject stub_GameGLSurfaceView_GameGLSurfaceView_132(jmethodID id, va_list args);
extern void stub_GameGLSurfaceView_checkEglError_133(jmethodID id, va_list args);
extern void stub_GameGLSurfaceView_onSizeChanged_134(jmethodID id, va_list args);
extern jboolean stub_GameGLSurfaceView_onTouchEvent_135(jmethodID id, va_list args);
extern void stub_GameGLSurfaceView_onWindowFocusChanged_136(jmethodID id, va_list args);
extern jobject stub_GameRenderer_GameRenderer_137(jmethodID id, va_list args);
extern void stub_GameRenderer_onDrawFrame_138(jmethodID id, va_list args);
extern void stub_GameRenderer_onSurfaceChanged_139(jmethodID id, va_list args);
extern void stub_GameRenderer_onSurfaceCreated_140(jmethodID id, va_list args);
extern void stub_MediaPlaylist_ChangeMusic_141(jmethodID id, va_list args);
extern jint stub_MediaPlaylist_DisablePlaylist_142(jmethodID id, va_list args);
extern jint stub_MediaPlaylist_GetCurrentPlaylist_143(jmethodID id, va_list args);
extern jint stub_MediaPlaylist_GetNumPlaylists_144(jmethodID id, va_list args);
extern jobject stub_MediaPlaylist_GetPlayListName_145(jmethodID id, va_list args);
extern void stub_MediaPlaylist_Init_146(jmethodID id, va_list args);
extern void stub_MediaPlaylist_PauseMusicBG_147(jmethodID id, va_list args);
extern void stub_MediaPlaylist_PlayBGMusic_148(jmethodID id, va_list args);
extern void stub_MediaPlaylist_ResumeMusicBG_149(jmethodID id, va_list args);
extern void stub_MediaPlaylist_SetPlaylist_150(jmethodID id, va_list args);
extern void stub_MediaPlaylist_StopMusicBG_151(jmethodID id, va_list args);
extern jint stub_MediaPlaylist_getListID_152(jmethodID id, va_list args);
extern jint stub_MediaPlaylist_hasSDCard_153(jmethodID id, va_list args);
extern void stub_MediaPlaylist_init_phone_music_grid_154(jmethodID id, va_list args);
extern void stub_MediaPlaylist_pauseMusic_155(jmethodID id, va_list args);
extern void stub_MediaPlaylist_playAList_156(jmethodID id, va_list args);
extern void stub_MediaPlaylist_playAList_157(jmethodID id, va_list args);
extern void stub_MediaPlaylist_playAList_158(jmethodID id, va_list args);
extern void stub_MediaPlaylist_playAList_159(jmethodID id, va_list args);
extern void stub_MediaPlaylist_playListResume_160(jmethodID id, va_list args);
extern void stub_MediaPlaylist_playMusic_161(jmethodID id, va_list args);
extern void stub_MediaPlaylist_playMusic_162(jmethodID id, va_list args);
extern void stub_MediaPlaylist_playMusic_163(jmethodID id, va_list args);
extern void stub_MediaPlaylist_reloadAndPlayMusic_164(jmethodID id, va_list args);
extern void stub_MediaPlaylist_resumeMusic_165(jmethodID id, va_list args);
extern void stub_MediaPlaylist_stopMusic_166(jmethodID id, va_list args);

// Candidate NameToMethodID entries -- append into the real nameToMethodId[] in java.c
static const NameToMethodID generated_nameToMethodId[] = {
    { 0, "getMusicDuration", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 1, "getSoundDuration", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 2, "getSoundStatus", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 3, "getVolume", METHOD_TYPE_FLOAT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 4, "init", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 5, "isMediaPlaying", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 6, "isMusicPlaying", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 7, "isSoundLoaded", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 8, "loadMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 9, "loadSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 10, "loadSoundPool", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 11, "pauseAllMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 12, "pauseAllSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 13, "pauseAllSounds", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 14, "pauseMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 15, "pauseMusicAsSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 16, "pauseSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 17, "playMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 18, "playMusicAsSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 19, "playSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 20, "resetSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 21, "resumeAllSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 22, "resumeMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 23, "resumeMusicAsSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 24, "resumeSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 25, "setVolume", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 26, "stopAllMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 27, "stopAllSounds", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 28, "stopMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 29, "stopMusicAsSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 30, "stopSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 31, "unloadMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 32, "unloadSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 33, "updateSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer
    { 34, "destroy", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader
    { 35, "getRawResource", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader
    { 36, "getResourceBytes", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader
    { 37, "getResourceFull", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader
    { 38, "getResourceFull", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader
    { 39, "getResourceLength", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader
    { 40, "getResourceLengthSoundRaw", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader
    { 41, "getSoundRaw", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader
    { 42, "getSoundRawIS", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader
    { 43, "getString", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader
    { 44, "init", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader
    { 45, "Device", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 46, "InitDeviceValues", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 47, "IsWifiEnable", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 48, "ValidateStringforURL", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 49, "a", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 50, "b", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 51, "c", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 52, "createUniqueCode", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 53, "d", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 54, "e", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 55, "f", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 56, "getCarrier", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 57, "getDemoCode", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 58, "getDevice", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 59, "getHostName", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 60, "getIMEI", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 61, "getIsRoaming", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 62, "getLanguage", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 63, "getLineNumber", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 64, "getNetworkCountryIso", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 65, "getNetworkOperator", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 66, "getNetworkOperatorName", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 67, "getPhoneModel", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 68, "getSimCountryIso", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 69, "getSimOperator", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 70, "getSimOperatorName", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 71, "getUniqueCode", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 72, "getUserAgent", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 73, "init", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device
    { 74, "Autologin", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 75, "Password", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 76, "UserName", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 77, "a", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 78, "autoScaleTextViewTextToWidth", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 79, "initBadge", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 80, "initialize_Trophy", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 81, "needToRemoveFacebook", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 82, "notifyTrophy", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 83, "updateBadge", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 84, "updateWebView", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 85, "writeLoginInfo", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 86, "a", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 87, "a", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 88, "a", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 89, "onCreate", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 90, "onDestroy", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 91, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 92, "onKeyLongPress", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 93, "onKeyUp", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 94, "onPause", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 95, "onResume", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 96, "onWindowFocusChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain
    { 97, "DismissSpinner", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 98, "Exit", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 99, "GetPhoneLanguage", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 100, "Pause", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 101, "SetReorientation", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 102, "ShowSpinner", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 103, "d", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 104, "da", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 105, "db", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 106, "dc", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 107, "enableWifi", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 108, "getManufacture", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 109, "isNeedGcOnFrame", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 110, "isNeedUsedTouchZone", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 111, "isWifiEnabled", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 112, "launchGLLive", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 113, "launchIGP", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 114, "launchIGP_SKT", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 115, "notifyTrophy", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 116, "openBrowser", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 117, "playVideo", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 118, "sendAppToBackground", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 119, "onAccuracyChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 120, "onCreate", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 121, "onDestroy", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 122, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 123, "onKeyLongPress", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 124, "onKeyUp", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 125, "onPause", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 126, "onRestart", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 127, "onResume", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 128, "onSearchRequested", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 129, "onSensorChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 130, "onStart", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 131, "onStop", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.Game
    { 132, "GameGLSurfaceView", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GameGLSurfaceView
    { 133, "checkEglError", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GameGLSurfaceView
    { 134, "onSizeChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GameGLSurfaceView
    { 135, "onTouchEvent", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSOHP.ML.GameGLSurfaceView
    { 136, "onWindowFocusChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GameGLSurfaceView
    { 137, "GameRenderer", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.GameRenderer
    { 138, "onDrawFrame", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GameRenderer
    { 139, "onSurfaceChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GameRenderer
    { 140, "onSurfaceCreated", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.GameRenderer
    { 141, "ChangeMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 142, "DisablePlaylist", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 143, "GetCurrentPlaylist", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 144, "GetNumPlaylists", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 145, "GetPlayListName", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 146, "Init", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 147, "PauseMusicBG", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 148, "PlayBGMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 149, "ResumeMusicBG", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 150, "SetPlaylist", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 151, "StopMusicBG", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 152, "getListID", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 153, "hasSDCard", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 154, "init_phone_music_grid", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 155, "pauseMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 156, "playAList", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 157, "playAList", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 158, "playAList", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 159, "playAList", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 160, "playListResume", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 161, "playMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 162, "playMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 163, "playMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 164, "reloadAndPlayMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 165, "resumeMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
    { 166, "stopMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist
};

// Candidate methodsInt[] entries -- append into the real methodsInt[] in java.c
static const MethodsInt generated_methodsInt[] = {
    { 0, stub_GLMediaPlayer_getMusicDuration_0 },
    { 1, stub_GLMediaPlayer_getSoundDuration_1 },
    { 2, stub_GLMediaPlayer_getSoundStatus_2 },
    { 5, stub_GLMediaPlayer_isMediaPlaying_5 },
    { 6, stub_GLMediaPlayer_isMusicPlaying_6 },
    { 7, stub_GLMediaPlayer_isSoundLoaded_7 },
    { 39, stub_GLResLoader_getResourceLength_39 },
    { 40, stub_GLResLoader_getResourceLengthSoundRaw_40 },
    { 52, stub_Device_createUniqueCode_52 },
    { 71, stub_Device_getUniqueCode_71 },
    { 99, stub_Game_GetPhoneLanguage_99 },
    { 108, stub_Game_getManufacture_108 },
    { 111, stub_Game_isWifiEnabled_111 },
    { 142, stub_MediaPlaylist_DisablePlaylist_142 },
    { 143, stub_MediaPlaylist_GetCurrentPlaylist_143 },
    { 144, stub_MediaPlaylist_GetNumPlaylists_144 },
    { 152, stub_MediaPlaylist_getListID_152 },
    { 153, stub_MediaPlaylist_hasSDCard_153 },
};

// Candidate methodsFloat[] entries -- append into the real methodsFloat[] in java.c
static const MethodsFloat generated_methodsFloat[] = {
    { 3, stub_GLMediaPlayer_getVolume_3 },
};

// Candidate methodsVoid[] entries -- append into the real methodsVoid[] in java.c
static const MethodsVoid generated_methodsVoid[] = {
    { 4, stub_GLMediaPlayer_init_4 },
    { 8, stub_GLMediaPlayer_loadMusic_8 },
    { 9, stub_GLMediaPlayer_loadSound_9 },
    { 10, stub_GLMediaPlayer_loadSoundPool_10 },
    { 11, stub_GLMediaPlayer_pauseAllMusic_11 },
    { 12, stub_GLMediaPlayer_pauseAllSound_12 },
    { 13, stub_GLMediaPlayer_pauseAllSounds_13 },
    { 14, stub_GLMediaPlayer_pauseMusic_14 },
    { 15, stub_GLMediaPlayer_pauseMusicAsSound_15 },
    { 16, stub_GLMediaPlayer_pauseSound_16 },
    { 17, stub_GLMediaPlayer_playMusic_17 },
    { 18, stub_GLMediaPlayer_playMusicAsSound_18 },
    { 19, stub_GLMediaPlayer_playSound_19 },
    { 20, stub_GLMediaPlayer_resetSound_20 },
    { 21, stub_GLMediaPlayer_resumeAllSound_21 },
    { 22, stub_GLMediaPlayer_resumeMusic_22 },
    { 23, stub_GLMediaPlayer_resumeMusicAsSound_23 },
    { 24, stub_GLMediaPlayer_resumeSound_24 },
    { 25, stub_GLMediaPlayer_setVolume_25 },
    { 26, stub_GLMediaPlayer_stopAllMusic_26 },
    { 27, stub_GLMediaPlayer_stopAllSounds_27 },
    { 28, stub_GLMediaPlayer_stopMusic_28 },
    { 29, stub_GLMediaPlayer_stopMusicAsSound_29 },
    { 30, stub_GLMediaPlayer_stopSound_30 },
    { 31, stub_GLMediaPlayer_unloadMusic_31 },
    { 32, stub_GLMediaPlayer_unloadSound_32 },
    { 33, stub_GLMediaPlayer_updateSound_33 },
    { 34, stub_GLResLoader_destroy_34 },
    { 44, stub_GLResLoader_init_44 },
    { 46, stub_Device_InitDeviceValues_46 },
    { 54, stub_Device_e_54 },
    { 73, stub_Device_init_73 },
    { 77, stub_GLiveMain_a_77 },
    { 78, stub_GLiveMain_autoScaleTextViewTextToWidth_78 },
    { 79, stub_GLiveMain_initBadge_79 },
    { 80, stub_GLiveMain_initialize_Trophy_80 },
    { 82, stub_GLiveMain_notifyTrophy_82 },
    { 83, stub_GLiveMain_updateBadge_83 },
    { 84, stub_GLiveMain_updateWebView_84 },
    { 85, stub_GLiveMain_writeLoginInfo_85 },
    { 86, stub_GLiveMain_a_86 },
    { 87, stub_GLiveMain_a_87 },
    { 88, stub_GLiveMain_a_88 },
    { 89, stub_GLiveMain_onCreate_89 },
    { 90, stub_GLiveMain_onDestroy_90 },
    { 94, stub_GLiveMain_onPause_94 },
    { 95, stub_GLiveMain_onResume_95 },
    { 96, stub_GLiveMain_onWindowFocusChanged_96 },
    { 97, stub_Game_DismissSpinner_97 },
    { 98, stub_Game_Exit_98 },
    { 100, stub_Game_Pause_100 },
    { 101, stub_Game_SetReorientation_101 },
    { 102, stub_Game_ShowSpinner_102 },
    { 103, stub_Game_d_103 },
    { 107, stub_Game_enableWifi_107 },
    { 112, stub_Game_launchGLLive_112 },
    { 113, stub_Game_launchIGP_113 },
    { 114, stub_Game_launchIGP_SKT_114 },
    { 115, stub_Game_notifyTrophy_115 },
    { 116, stub_Game_openBrowser_116 },
    { 117, stub_Game_playVideo_117 },
    { 118, stub_Game_sendAppToBackground_118 },
    { 119, stub_Game_onAccuracyChanged_119 },
    { 120, stub_Game_onCreate_120 },
    { 121, stub_Game_onDestroy_121 },
    { 125, stub_Game_onPause_125 },
    { 126, stub_Game_onRestart_126 },
    { 127, stub_Game_onResume_127 },
    { 129, stub_Game_onSensorChanged_129 },
    { 130, stub_Game_onStart_130 },
    { 131, stub_Game_onStop_131 },
    { 133, stub_GameGLSurfaceView_checkEglError_133 },
    { 134, stub_GameGLSurfaceView_onSizeChanged_134 },
    { 136, stub_GameGLSurfaceView_onWindowFocusChanged_136 },
    { 138, stub_GameRenderer_onDrawFrame_138 },
    { 139, stub_GameRenderer_onSurfaceChanged_139 },
    { 140, stub_GameRenderer_onSurfaceCreated_140 },
    { 141, stub_MediaPlaylist_ChangeMusic_141 },
    { 146, stub_MediaPlaylist_Init_146 },
    { 147, stub_MediaPlaylist_PauseMusicBG_147 },
    { 148, stub_MediaPlaylist_PlayBGMusic_148 },
    { 149, stub_MediaPlaylist_ResumeMusicBG_149 },
    { 150, stub_MediaPlaylist_SetPlaylist_150 },
    { 151, stub_MediaPlaylist_StopMusicBG_151 },
    { 154, stub_MediaPlaylist_init_phone_music_grid_154 },
    { 155, stub_MediaPlaylist_pauseMusic_155 },
    { 156, stub_MediaPlaylist_playAList_156 },
    { 157, stub_MediaPlaylist_playAList_157 },
    { 158, stub_MediaPlaylist_playAList_158 },
    { 159, stub_MediaPlaylist_playAList_159 },
    { 160, stub_MediaPlaylist_playListResume_160 },
    { 161, stub_MediaPlaylist_playMusic_161 },
    { 162, stub_MediaPlaylist_playMusic_162 },
    { 163, stub_MediaPlaylist_playMusic_163 },
    { 164, stub_MediaPlaylist_reloadAndPlayMusic_164 },
    { 165, stub_MediaPlaylist_resumeMusic_165 },
    { 166, stub_MediaPlaylist_stopMusic_166 },
};

// Candidate methodsObject[] entries -- append into the real methodsObject[] in java.c
static const MethodsObject generated_methodsObject[] = {
    { 35, stub_GLResLoader_getRawResource_35 },
    { 36, stub_GLResLoader_getResourceBytes_36 },
    { 37, stub_GLResLoader_getResourceFull_37 },
    { 38, stub_GLResLoader_getResourceFull_38 },
    { 41, stub_GLResLoader_getSoundRaw_41 },
    { 42, stub_GLResLoader_getSoundRawIS_42 },
    { 43, stub_GLResLoader_getString_43 },
    { 45, stub_Device_Device_45 },
    { 48, stub_Device_ValidateStringforURL_48 },
    { 49, stub_Device_a_49 },
    { 50, stub_Device_b_50 },
    { 51, stub_Device_c_51 },
    { 53, stub_Device_d_53 },
    { 55, stub_Device_f_55 },
    { 56, stub_Device_getCarrier_56 },
    { 57, stub_Device_getDemoCode_57 },
    { 58, stub_Device_getDevice_58 },
    { 59, stub_Device_getHostName_59 },
    { 60, stub_Device_getIMEI_60 },
    { 62, stub_Device_getLanguage_62 },
    { 63, stub_Device_getLineNumber_63 },
    { 64, stub_Device_getNetworkCountryIso_64 },
    { 65, stub_Device_getNetworkOperator_65 },
    { 66, stub_Device_getNetworkOperatorName_66 },
    { 67, stub_Device_getPhoneModel_67 },
    { 68, stub_Device_getSimCountryIso_68 },
    { 69, stub_Device_getSimOperator_69 },
    { 70, stub_Device_getSimOperatorName_70 },
    { 72, stub_Device_getUserAgent_72 },
    { 75, stub_GLiveMain_Password_75 },
    { 76, stub_GLiveMain_UserName_76 },
    { 104, stub_Game_da_104 },
    { 105, stub_Game_db_105 },
    { 106, stub_Game_dc_106 },
    { 132, stub_GameGLSurfaceView_GameGLSurfaceView_132 },
    { 137, stub_GameRenderer_GameRenderer_137 },
    { 145, stub_MediaPlaylist_GetPlayListName_145 },
};

// Candidate methodsBoolean[] entries -- append into the real methodsBoolean[] in java.c
static const MethodsBoolean generated_methodsBoolean[] = {
    { 47, stub_Device_IsWifiEnable_47 },
    { 61, stub_Device_getIsRoaming_61 },
    { 74, stub_GLiveMain_Autologin_74 },
    { 81, stub_GLiveMain_needToRemoveFacebook_81 },
    { 91, stub_GLiveMain_onKeyDown_91 },
    { 92, stub_GLiveMain_onKeyLongPress_92 },
    { 93, stub_GLiveMain_onKeyUp_93 },
    { 109, stub_Game_isNeedGcOnFrame_109 },
    { 110, stub_Game_isNeedUsedTouchZone_110 },
    { 122, stub_Game_onKeyDown_122 },
    { 123, stub_Game_onKeyLongPress_123 },
    { 124, stub_Game_onKeyUp_124 },
    { 128, stub_Game_onSearchRequested_128 },
    { 135, stub_GameGLSurfaceView_onTouchEvent_135 },
};

