/* Auto-generated by psvita-toolkit -- see generated_jni_table.h */
#include <falso_jni/FalsoJNI_Impl.h>
#include "generated_jni_table.h"

// ---- com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer ----
jint stub_GLMediaPlayer_getMusicDuration_0(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.getMusicDuration(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

jint stub_GLMediaPlayer_getSoundDuration_1(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.getSoundDuration(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

jint stub_GLMediaPlayer_getSoundStatus_2(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.getSoundStatus(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

jfloat stub_GLMediaPlayer_getVolume_3(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.getVolume(I)F called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0.0f;
}

void stub_GLMediaPlayer_init_4(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.init()V called -- fill in from the real Java impl (jadx).");
}

jint stub_GLMediaPlayer_isMediaPlaying_5(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.isMediaPlaying(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

jint stub_GLMediaPlayer_isMusicPlaying_6(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.isMusicPlaying(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

jint stub_GLMediaPlayer_isSoundLoaded_7(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.isSoundLoaded(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

void stub_GLMediaPlayer_loadMusic_8(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.loadMusic(ILjava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_GLMediaPlayer_loadSound_9(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.loadSound(ILjava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_GLMediaPlayer_loadSoundPool_10(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.loadSoundPool(ILjava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_GLMediaPlayer_pauseAllMusic_11(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.pauseAllMusic()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_pauseAllSound_12(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.pauseAllSound()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_pauseAllSounds_13(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.pauseAllSounds()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_pauseMusic_14(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.pauseMusic(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_pauseMusicAsSound_15(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.pauseMusicAsSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_pauseSound_16(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.pauseSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_playMusic_17(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.playMusic(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_playMusicAsSound_18(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.playMusicAsSound(IILjava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);
}

void stub_GLMediaPlayer_playSound_19(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.playSound(IILjava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);
}

void stub_GLMediaPlayer_resetSound_20(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.resetSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_resumeAllSound_21(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.resumeAllSound()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_resumeMusic_22(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.resumeMusic(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_resumeMusicAsSound_23(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.resumeMusicAsSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_resumeSound_24(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.resumeSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_setVolume_25(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.setVolume(IF)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jfloat arg1 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_stopAllMusic_26(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.stopAllMusic()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_stopAllSounds_27(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.stopAllSounds()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_stopMusic_28(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.stopMusic(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_stopMusicAsSound_29(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.stopMusicAsSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_stopSound_30(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.stopSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_unloadMusic_31(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.unloadMusic(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_unloadSound_32(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.unloadSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_updateSound_33(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLMediaPlayer.updateSound()V called -- fill in from the real Java impl (jadx).");
}

// ---- com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader ----
void stub_GLResLoader_destroy_34(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader.destroy()V called -- fill in from the real Java impl (jadx).");
}

jbyteArray stub_GLResLoader_getRawResource_35(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader.getRawResource(ILContext;)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jbyteArray stub_GLResLoader_getResourceBytes_36(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader.getResourceBytes(Ljava/lang/String;II)[B called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
    return NULL;
}

jbyteArray stub_GLResLoader_getResourceFull_37(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader.getResourceFull(I)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

jbyteArray stub_GLResLoader_getResourceFull_38(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader.getResourceFull(Ljava/lang/String;)[B called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jint stub_GLResLoader_getResourceLength_39(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader.getResourceLength(Ljava/lang/String;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return 0;
}

jint stub_GLResLoader_getResourceLengthSoundRaw_40(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader.getResourceLengthSoundRaw(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

jbyteArray stub_GLResLoader_getSoundRaw_41(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader.getSoundRaw(I)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

jobject stub_GLResLoader_getSoundRawIS_42(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader.getSoundRawIS(I)LInputStream; called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

jobject stub_GLResLoader_getString_43(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader.getString(ILContext;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_GLResLoader_init_44(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLResLoader.init()V called -- fill in from the real Java impl (jadx).");
}

// ---- com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device ----
jobject stub_Device_Device_45(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.Device()Lpublic; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_Device_InitDeviceValues_46(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.InitDeviceValues()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_Device_IsWifiEnable_47(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.IsWifiEnable()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jobject stub_Device_ValidateStringforURL_48(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.ValidateStringforURL(Ljava/lang/String;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jbyteArray stub_Device_a_49(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.a()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Device_b_50(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.b()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Device_c_51(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.c()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jint stub_Device_createUniqueCode_52(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.createUniqueCode()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jbyteArray stub_Device_d_53(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.d()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_Device_e_54(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.e(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

jbyteArray stub_Device_f_55(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.f()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getCarrier_56(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getCarrier()Ld; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getDemoCode_57(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getDemoCode()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getDevice_58(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getDevice()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Device_getHostName_59(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getHostName()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getIMEI_60(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getIMEI()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jboolean stub_Device_getIsRoaming_61(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getIsRoaming()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jobject stub_Device_getLanguage_62(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getLanguage(Ljava/lang/String;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jobject stub_Device_getLineNumber_63(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getLineNumber()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getNetworkCountryIso_64(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getNetworkCountryIso()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getNetworkOperator_65(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getNetworkOperator()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getNetworkOperatorName_66(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getNetworkOperatorName()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getPhoneModel_67(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getPhoneModel()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getSimCountryIso_68(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getSimCountryIso()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getSimOperator_69(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getSimOperator()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getSimOperatorName_70(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getSimOperatorName()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jint stub_Device_getUniqueCode_71(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getUniqueCode()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jobject stub_Device_getUserAgent_72(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.getUserAgent()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_Device_init_73(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLUtils.Device.init()V called -- fill in from the real Java impl (jadx).");
}

// ---- com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain ----
jboolean stub_GLiveMain_Autologin_74(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.Autologin()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jobject stub_GLiveMain_Password_75(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.Password()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_GLiveMain_UserName_76(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.UserName()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_GLiveMain_a_77(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.a()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLiveMain_autoScaleTextViewTextToWidth_78(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.autoScaleTextViewTextToWidth(LTextView;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_GLiveMain_initBadge_79(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.initBadge(LTextView;Ljava/lang/String;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_GLiveMain_initialize_Trophy_80(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.initialize_Trophy([I)V called -- fill in from the real Java impl (jadx).");
    jintArray arg0 = (jintArray) va_arg(args, jobject);
}

jboolean stub_GLiveMain_needToRemoveFacebook_81(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.needToRemoveFacebook()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_GLiveMain_notifyTrophy_82(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.notifyTrophy(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLiveMain_updateBadge_83(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.updateBadge(LTextView;Ljava/lang/String;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_GLiveMain_updateWebView_84(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.updateWebView()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLiveMain_writeLoginInfo_85(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.writeLoginInfo()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLiveMain_a_86(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.a(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLiveMain_a_87(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.a(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);
    jobject arg2 = (jobject) va_arg(args, jobject);
    jobject arg3 = (jobject) va_arg(args, jobject);
}

void stub_GLiveMain_a_88(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.a(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_GLiveMain_onCreate_89(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GLiveMain_onDestroy_90(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_GLiveMain_onKeyDown_91(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_GLiveMain_onKeyLongPress_92(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.onKeyLongPress(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_GLiveMain_onKeyUp_93(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.onKeyUp(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_GLiveMain_onPause_94(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLiveMain_onResume_95(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLiveMain_onWindowFocusChanged_96(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GLiveMain.onWindowFocusChanged(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

// ---- com.gameloft.android.ANMP.GloftSOHP.ML.Game ----
void stub_Game_DismissSpinner_97(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.DismissSpinner()V called -- fill in from the real Java impl (jadx).");
}

void stub_Game_Exit_98(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.Exit()V called -- fill in from the real Java impl (jadx).");
}

jint stub_Game_GetPhoneLanguage_99(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.GetPhoneLanguage()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

void stub_Game_Pause_100(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.Pause()V called -- fill in from the real Java impl (jadx).");
}

void stub_Game_SetReorientation_101(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.SetReorientation(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_Game_ShowSpinner_102(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.ShowSpinner(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_Game_d_103(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.d()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_Game_da_104(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.da()LActivity; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Game_db_105(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.db()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Game_dc_106(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.dc()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_Game_enableWifi_107(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.enableWifi(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

jint stub_Game_getManufacture_108(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.getManufacture()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jboolean stub_Game_isNeedGcOnFrame_109(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.isNeedGcOnFrame()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jboolean stub_Game_isNeedUsedTouchZone_110(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.isNeedUsedTouchZone()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jint stub_Game_isWifiEnabled_111(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.isWifiEnabled()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

void stub_Game_launchGLLive_112(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.launchGLLive(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_Game_launchIGP_113(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.launchIGP(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_Game_launchIGP_SKT_114(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.launchIGP_SKT(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_Game_notifyTrophy_115(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.notifyTrophy(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_Game_openBrowser_116(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.openBrowser(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_Game_playVideo_117(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.playVideo(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_Game_sendAppToBackground_118(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.sendAppToBackground()V called -- fill in from the real Java impl (jadx).");
}

void stub_Game_onAccuracyChanged_119(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onAccuracyChanged(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_Game_onCreate_120(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_Game_onDestroy_121(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_Game_onKeyDown_122(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_Game_onKeyLongPress_123(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onKeyLongPress(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_Game_onKeyUp_124(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onKeyUp(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_Game_onPause_125(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_Game_onRestart_126(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onRestart()V called -- fill in from the real Java impl (jadx).");
}

void stub_Game_onResume_127(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onResume()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_Game_onSearchRequested_128(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onSearchRequested()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_Game_onSensorChanged_129(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onSensorChanged(I[F)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jfloatArray arg1 = (jfloatArray) va_arg(args, jobject);
}

void stub_Game_onStart_130(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onStart()V called -- fill in from the real Java impl (jadx).");
}

void stub_Game_onStop_131(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.Game.onStop()V called -- fill in from the real Java impl (jadx).");
}

// ---- com.gameloft.android.ANMP.GloftSOHP.ML.GameGLSurfaceView ----
jobject stub_GameGLSurfaceView_GameGLSurfaceView_132(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GameGLSurfaceView.GameGLSurfaceView(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_GameGLSurfaceView_checkEglError_133(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GameGLSurfaceView.checkEglError(Ljava/lang/String;LEGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GameGLSurfaceView_onSizeChanged_134(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GameGLSurfaceView.onSizeChanged(IIII)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
    jint arg3 = (jint) va_arg(args, int);
}

jboolean stub_GameGLSurfaceView_onTouchEvent_135(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GameGLSurfaceView.onTouchEvent(LMotionEvent;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_GameGLSurfaceView_onWindowFocusChanged_136(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GameGLSurfaceView.onWindowFocusChanged(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

// ---- com.gameloft.android.ANMP.GloftSOHP.ML.GameRenderer ----
jobject stub_GameRenderer_GameRenderer_137(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GameRenderer.GameRenderer(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_GameRenderer_onDrawFrame_138(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GameRenderer.onDrawFrame(LGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GameRenderer_onSurfaceChanged_139(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GameRenderer.onSurfaceChanged(LGL10;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_GameRenderer_onSurfaceCreated_140(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.GameRenderer.onSurfaceCreated(LGL10;LEGLConfig;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist ----
void stub_MediaPlaylist_ChangeMusic_141(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.ChangeMusic(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

jint stub_MediaPlaylist_DisablePlaylist_142(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.DisablePlaylist()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jint stub_MediaPlaylist_GetCurrentPlaylist_143(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.GetCurrentPlaylist()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jint stub_MediaPlaylist_GetNumPlaylists_144(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.GetNumPlaylists()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jbyteArray stub_MediaPlaylist_GetPlayListName_145(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.GetPlayListName(I)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

void stub_MediaPlaylist_Init_146(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.Init()V called -- fill in from the real Java impl (jadx).");
}

void stub_MediaPlaylist_PauseMusicBG_147(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.PauseMusicBG()V called -- fill in from the real Java impl (jadx).");
}

void stub_MediaPlaylist_PlayBGMusic_148(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.PlayBGMusic()V called -- fill in from the real Java impl (jadx).");
}

void stub_MediaPlaylist_ResumeMusicBG_149(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.ResumeMusicBG()V called -- fill in from the real Java impl (jadx).");
}

void stub_MediaPlaylist_SetPlaylist_150(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.SetPlaylist(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_MediaPlaylist_StopMusicBG_151(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.StopMusicBG()V called -- fill in from the real Java impl (jadx).");
}

jint stub_MediaPlaylist_getListID_152(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.getListID(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

jint stub_MediaPlaylist_hasSDCard_153(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.hasSDCard()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

void stub_MediaPlaylist_init_phone_music_grid_154(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.init_phone_music_grid()V called -- fill in from the real Java impl (jadx).");
}

void stub_MediaPlaylist_pauseMusic_155(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.pauseMusic()V called -- fill in from the real Java impl (jadx).");
}

void stub_MediaPlaylist_playAList_156(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.playAList(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_MediaPlaylist_playAList_157(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.playAList(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_MediaPlaylist_playAList_158(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.playAList(LCursor;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_MediaPlaylist_playAList_159(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.playAList(LCursor;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
}

void stub_MediaPlaylist_playListResume_160(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.playListResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_MediaPlaylist_playMusic_161(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.playMusic(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_MediaPlaylist_playMusic_162(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.playMusic(Ljava/lang/String;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_MediaPlaylist_playMusic_163(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.playMusic(Ljava/lang/String;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_MediaPlaylist_reloadAndPlayMusic_164(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.reloadAndPlayMusic(Ljava/lang/String;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_MediaPlaylist_resumeMusic_165(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.resumeMusic()V called -- fill in from the real Java impl (jadx).");
}

void stub_MediaPlaylist_stopMusic_166(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSOHP.ML.MediaPlaylist.stopMusic()V called -- fill in from the real Java impl (jadx).");
}

